
#include "AdvancedAudioEncoding.h"

int main()
{
	AdvancedAudioEncoding audioEncoding;

	// use the pcm file generated by decoding mp3 file as input
	const char *inFile = "../assets/s16.pcm";
	const char *outFile = "../assets/fltp.aac";

	audioEncoding.init();

	// Configure AVCodecContext parameters Manually
	audioEncoding.initCodecContext();

	audioEncoding.readFrameProc(inFile, outFile);
}
